tailwindlabs/prettier-plugin-tailwindcss

- src/index.js
- tests/test.js
Hi there, I encountered a crash when running the plugin on a svelte file that has a slot component like this:
```svelte
<p
slot="test"
let:class={className}
class="h-full w-full p-2 backdrop-blur-0 {className}"
/>
```
Below was the error message and I've got a repro [here](https://github.com/chrsep/tailwind-prettier-sveltekit-repro):
I found that the plugin was trying to read the "value" attribute from the let directive, which is always undefined. So to avoid this, I added a check to make sure that the sorting only runs on the class attributes, not on a directive named class such as `let:class={className}`.
> Fix crash when formatting svelte files that have "let:class".

- src/index.js
Fixes #40
This PR adds a default value for the `options` parameter as sometimes this can be `undefined`
> Fix error when no Prettier options provided

- package-lock.json
- package.json
- src/index.js
- tests/test.js
Fixes #48
This PR works around `recast` converting single quotes to double quotes in strings in some cases (https://github.com/benjamn/recast/issues/171)
> Fix single quotes being converted to double quotes

- package-lock.json
- package.json
- src/index.js
- tests/test.js
This PR will use Tailwind's exposed `context.getClassOrder(classes)` function instead. This will allow us to have some special cases in Tailwind itself (e.g.: `group` and `peer`). But it will also make sure that the actual sorting logic stays in this plugin. 
Tailwind will just expose the information required to be able to sort classes correctly. When classes are unknown, the sort order will be set to `null`.
Fixes: #53
> Use Tailwind's `context.getClassOrder(classes)`

- package-lock.json
- package.json
- prettier.config.js
- src/index.js
- tests/fixtures/basic/prettier.config.js
- tests/fixtures/cjs/prettier.config.js
- tests/fixtures/no-prettier-config/index.html
- tests/fixtures/no-prettier-config/tailwind.config.js
- tests/test.js
This PR fixes Tailwind config file resolution when no Prettier config file is present. Now, when the `tailwindConfig` option is not provided the plugin will search up the directory hierarchy from a "base" directory, looking for a config file. The base directory is determined in this order:
1. The directory containing the Prettier config file if there is one
2. The directory containing the current file (`options.filepath`), if provided
3. The current working directory (`process.cwd()`)
Additionally, the `VSCODE_CWD` environment variable is no longer used because its value is not necessarily equal to the directory that is currently open in VS Code, as originally thought.
> Fix Tailwind config file resolution when Prettier config file is not present

- src/index.js
- tests/test.js
This PR reverts #70 due to unforeseen [issues](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/71) with whitespace removal
> Revert #70

- src/index.js
- tests/test.js
> Fix sorting in Svelte `:else` blocks

- .vscode/settings.json
- package-lock.json
- package.json
- src/index.js
- tests/test.js
Hello!
I'm Erika from the [Astro](https://astro.build/) team. [We love Tailwind](https://docs.astro.build/en/guides/integrations-guide/tailwind/) and would love to have support for Astro files inside this plugin. As such, well, here's a PR that adds it 😄
The support is pretty good, since we use other parsers for the different parts of the files, including expressions:
```astro
---
...
---
<div class="p-20 w-full bg-red-100"></div>
{<div class="p-20 w-full bg-red-100"></div>}
<style>
h1 {
@apply p-20 w-full bg-fuchsia-50;
}
</style>
```
I hope we can get this to work, don't hesitate if there's anything needed from us to get this over the line!
Thank you
> Add support for formatting `.astro` files

- src/index.js
- tests/test.js
Angular's internal `__ng_directive` parser outright fails when given an expression like `foo?.[anything_can_go_here]` so we'll try it and then fall back to JS expression parsing if it fails.
Fixes #91
> Fallback to js expression parsing for angular directives if needed

- build.js
- package-lock.json
- package.json
- src/index.js
- tests/plugins.test.js
- tests/test.js
Prettier itself does not allow for multiple parsers covering the same AST / language at one time. This means that plugins that override existing languages are inherently incompatible.
However, with Prettier, it's common to take one of the built-in parsers, copy it, and mutate the preprocess or parse methods (we do this as well). This PR attempts to enable compatibility with _specific plugins_ that extend / overwrite Prettier's built-in parsers by deferring to the parsers from the plugin instead.
This requires two things:
1. You MUST customize your plugins and not rely on autoloading. This is because, when autoloading, the order is not defined.
2. You MUST put `prettier-plugin-tailwindcss` _last_.
This PR also enables us to no longer bundle the Svelte plugin. There's still complicated …
> Work on external plugin compat

- package-lock.json
- package.json
- src/index.js
- tests/plugins.test.js
This PR adds support for `@shopify/prettier-plugin-liquid`. Just don't look at the code 🙈
> Add support for `@shopify/prettier-plugin-liquid`

- CHANGELOG.md
- package-lock.json
- package.json
- src/index.js
The v1.0 release candidates of the plugin broke class attribute detection. This fixes that.
Fixes #108
> Fix support for latest Liquid scripting plugin

- package-lock.json
- package.json
Fixes #112 
I tested it by publishing it to a private npm registry.
You can test it for yourself (the yarn cache is checked into the repo): https://github.com/notpeelz/bug-repro-prettier-tw-sort-imports/tree/fixed
> Add prettier plugins to peer dependencies

- CHANGELOG.md
- src/index.js
- tests/test.js
Glimmer supports concatenation via the `(concat)` helper.
The plugin is currently incorrectly breaking up the concatenation
I first added a failing test showing the issue.
Use ignoreLast in a Glimmer StringLiteral if the parent is a SubExpression (meaning helper) and the last character of the node value is not whitespace
Meaning `(concat "border-l-blue border-" @color)` does not get sorted
While `(concat "border-l-blue border ")` does get sorted
> Fix Glimmer Concatenation

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/index.js
- tests/plugins.test.js
I edited this in GH so commits aren't squashed, but yolo.
@ianvs/prettier-plugin-sort-imports fork has been better and preserves order of side-effect imports.
> Ianvs prettier plugin sort imports

- CHANGELOG.md
- src/index.js
- tests/test.js
> Add support for sorting `class` attribute on Astro components

- CHANGELOG.md
- src/index.js
- tests/plugins.test.js
> Fix class sorting in `capture` liquid tag

- src/index.js
- tests/plugins.test.js
The current approach doesn't uniformly change all sources in all AST nodes. This results in weird behavior where only the first or last tag may end up sorted.
Because we're somewhat relying on implementation details here (the use of `.source` + `.position` across various nodes rather than the values embedded in the AST) we want to make sure all changes for all classes are applied across all traversed instances of the source text in the AST.
Fixes #130 (for real this time)
> Fix Liquid `capture` sorting

- package-lock.json
- package.json
- scripts/install-fixture-deps.js
- src/index.js
- tests/fixtures/esm-explicit/config.mjs
- tests/fixtures/esm-explicit/index.html
- tests/fixtures/esm-explicit/prettier.config.js
- tests/fixtures/esm/index.html
- tests/fixtures/esm/prettier.config.js
- tests/fixtures/esm/tailwind.config.mjs
- tests/fixtures/ts-explicit/config.ts
- tests/fixtures/ts-explicit/index.html
- tests/fixtures/ts-explicit/prettier.config.js
- tests/fixtures/ts/index.html
- tests/fixtures/ts/prettier.config.js
- tests/fixtures/ts/tailwind.config.ts
- tests/fixtures/v3-2/index.html
- tests/fixtures/v3-2/package-lock.json
- tests/fixtures/v3-2/package.json
- tests/fixtures/v3-2/prettier.config.js
- tests/fixtures/v3-2/tailwind.config.js
- tests/test.js
Fixes: #136
Not sure I'll be able to fix this but added some failing tests atleast
> Support ESM and TS config files

- package-lock.json
- package.json
- src/index.js
This PR updates the `tailwindcss` module resolution so that it won't look further up the tree after finding the first instance of `tailwindcss`
> Load modules from nearest `tailwindcss` instance

- CHANGELOG.md
- src/compat.js
- src/config.js
- src/expiring-map.js
- src/index.js
- src/sorting.js
- src/utils.js
- tests/plugins.test.js
- tests/test.js
The way this plugin works currently is that for every invocation of `parse` by Prettier we:
- Load compatible plugins (if available)
- Locate the Tailwind config
- Load the config
- Create a context (if the config hasn't changed)
However, in plugins like Svelte or Vue that handle mixed languages, `parse` is called for every single JS or TypeScript expression. When there's a lot of them all of the above happens once for every single expression in a Svelte or Vue file 😱. Doing this once or twice total isn't a big deal — but if your file has hundreds of expressions, dynamic attributes, etc… this time adds up.
With this change we now do this at most once per source file per 5s interval (this is subject to change). The time interval lets us handle changes to the Tailwind CSS config without …
> Speed up formatting

- CHANGELOG.md
- src/compat.js
> Fix plugin compatibility when loaded with require

- CHANGELOG.md
- src/index.js
- tests/plugins.test.js
Given the following:
```liquid
<div class="sm:p-4 p-2 foo--{{ id }}"></div>
```
We would end up sorting it to the following (which is incorrect):
```liquid
<div class="foo-- p-2 sm:p-4 {{ id }}"></div>
```
Now, matching the behavior of template literals in JS and expressions in Svelte we now sort it like this instead:
```liquid
<div class="p-2 sm:p-4 foo--{{ id }}"></div>
```
Fixes #163
> Don't move partial classes inside Liquid script attributes

- CHANGELOG.md
- build.js
- src/config.js
- src/index.d.ts
- src/index.js
- src/options.js
- src/types.d.ts
> Export types

- CHANGELOG.md
- src/sorting.js
- tests/test.js
Hello, recently applying `prettier-plugin-tailwindcss` broke our styling :sob: so here is a fix.
According to the [web standard](https://dom.spec.whatwg.org/#concept-getelementsbyclassname), HTML's `class` attribute is split by ASCII whitespace into a set of classes. In other words, non-ASCII whitespace characters are not class separators.
For example, `px-1　py-2` is one class (notice that the spece in between is a U+3000), not two classes (`px-1` and `py-2`).
However, this plugin wrongly treats non-ASCII whitespace as a class separator, which may lead to unintended change of meaning of code.
The concrete scenario is that, when I newly applied `prettier-plugin-tailwindcss` to our project there was code like:
```jsx
<div className="relative w-full px-1[U+3000]z-10" />
```
where `px-1` and …
> Do not split classes by non-ASCII whitespace

- CHANGELOG.md
- src/index.js
- tests/fixtures/custom-jsx/index.jsx
- tests/fixtures/custom-jsx/prettier.config.js
- tests/test.js
> Match tagged template literals with tag expressions

- .github/workflows/prepare-release.yml
- .github/workflows/release.yml
- package.json
- scripts/release-channel.js
- scripts/release-notes.js
This PR adds workflows for release new versions of this plugin.
When you push a `tag` to the repo the following things will happen:
1. The `prepare-release` workflow will be executed, and this will open a draft release on GitHub for
the current version with the release notes found in the `CHANGELOG.md` for this version.
2. Once you are happy with this draft (you can edit the contents if you want), then you can publish
the release on GitHub.
3. This triggers a new workflow that will publish the version to `npm`.
This is the same behaviour that we have on various other repo's.
> Setup release workflows

- CHANGELOG.md
- src/plugin-v2.js
- src/plugin-v3.js
- tests/plugins.test.js
This is the same as #164 but for Twig / Melody.
Given:
```html
<div class="sm:p-4 p-2 text-{{ i }}"></div>
```
Before PR (incorrect):
```html
<div class="text- p-2 sm:p-4{{ i }}"></div>
```
After PR (correct):
```html
<div class="p-2 sm:p-4 text-{{ i }}"></div>
```
Fixes #183
> Don't move partial classes inside Twig attributes

- CHANGELOG.md
- src/plugin-v2.js
- src/plugin-v3.js
- tests/plugins.test.js
Hello!
I recently got to know the Astro framework and have been playing around with a practice project for the past few days.
However, when using the [`class:list` directive](https://docs.astro.build/en/reference/directives-reference/#classlist), even if the `tailwindAttributes: ['class:list']` option is set, classes are not sorted, so I opened this PR.
> Support `class:list` directive of Astro

- CHANGELOG.md
- build.mjs
- package-lock.json
We bundle several dependencies into the `dist/index.mjs` file. Previously, the build was CJS and everything "just worked" but now that it's ESM-only some top-level constants like `__filename` and `__dirname` are not defined and esbuild doesn't handle that for us :( Additionally, `require.cache` isn't passed through to `createRequire(…).cache` so we do that as well.
I think in an ideal world world we'd somehow split all bundled CJS dependencies into a separate `.cjs` file to allow everything to be handled by node itself. I'm not sure what that looks like at the moment though.
Fix for #198 (I hope 😅)
> Fix interop with bundled CJS dependencies

- build.mjs
Fixes #203
Tested on Windows 11 64
Should probably also be tested on other platforms. Any ideas how we can do that easily?
> Fix CJS __dirname interop on windows

- src/index.d.ts
Recently stumbled upon this error, which there is already a workaround here: https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/161#issuecomment-1555182516
It seems that in #162 these optional arguments were made necessary. See more below.
Before
```ts
export interface RawOptions {
tailwindConfig?: string
tailwindFunctions?: string[]
tailwindAttributes?: string[]
}
```
After
```ts
export interface PluginOptions {
/**
* Path to the Tailwind config file.
*/
tailwindConfig?: string
/**
* List of custom function and tag names that contain classes.
*/
tailwindFunctions: string[]
/**
* List of custom attributes that contain classes.
*/
tailwindAttributes: string[]
}
```
> fix(types): make `tailwindFunctions` and `tailwindAttributes` optional

- CHANGELOG.md
- src/index.js
- tests/format.test.js
The syntax `@apply … #{!important}` was already handled but SCSS allows one to wrap the inside portion in any number of matched single or double quotes so we check for that as well.
Fixes #211
> Don’t break `@apply … #{'!important'}` sorting

- CHANGELOG.md
- package-lock.json
- src/index.js
- tests/plugins.test.js
When using Astro with React you’d also want to sort `className` in addition to `class` and `class:list`. While we might be able to do some work to figure out if the element the attribute is on is a React component it seems unnecessary and I think it’s reasonable to have this enabled all the time.
Fixes #213
> Sort classes inside `className` in Astro

- CHANGELOG.md
- package.json
- src/index.js
- tests/fixtures.test.js
- tests/fixtures/custom-jsx/index.jsx
We support member access for tagged template literals when you specify custom sortable functions.
For example — the following:
```js
module.exports = {
tailwindFunctions: ['tw'],
}
```
Can sort these:
```js
const a = tw`sm:p-1 p-2`
const b = tw.foo`sm:p-1 p-2`
const c = tw.foo.bar`sm:p-1 p-2`
```
This PR adds support for function calls / `CallExpression` so it works in this case too:
```js
const a = tw("sm:p-1 p-2")
const b = tw.foo("sm:p-1 p-2")
const c = tw.foo.bar("sm:p-1 p-2")
```
> Support member access on function calls

- src/options.js
- tests/fixtures.test.js
- tests/fixtures/custom-vue/index.vue
Previously in the for loop for dynamicAttrs "attr.name" was added in the string template (which was undefined) while the required value was "attr" itself.
e.g. tailwindAttributes: ["ui"],
Before:
staticAttrs: "class,ui"
dynamicAttrs: ":class,v-bind:class,:undefined,v-bind:undefined"
After:
staticAttrs: "class,ui"
dynamicAttrs: ":class,v-bind:class,:ui,v-bind:ui"
fixes [Prettier Plugin Tailwind within :ui={...}](https://github.com/nuxt/ui/issues/776) and [[Prettier Plugin] Can't seem to get "tailwindAttributes" and/or "tailwindFunctions" to work?](https://github.com/tailwindlabs/tailwindcss/discussions/12270)
> Fix dynamicAttrs options.js

- CHANGELOG.md
- package-lock.json
- package.json
Happy release day! ✨ 
You can use this plugin with v3.4 without this update! This is just for those of you who use the CDN or a standalone binary and don't install Tailwind itself into your project but only have a config file. :)
> Bump bundled version of Tailwind CSS to v3.4

- CHANGELOG.md
- package-lock.json
- package.json
- src/config.js
- src/index.d.ts
- src/options.js
- src/types.d.ts
This adds support for sorting classes when using Tailwind CSS v4. Right now you must specify a `tailwindEntrypoint` config option and we'll process that with `postcss-import` to load the design system that Tailwind sees.
> Add preliminary support for v4

- .github/workflows/release-insiders.yml
- .github/workflows/release.yml
This commit adds provenance for all published packages. See the NPM documentation [0].
Provenance will allow people to verify that the packages were actually built on GH Actions and with the content of the corresponding commit. This will help with supply chain security.
For this to work, the `id-token` permission was added only where necessary.
[0]: https://docs.npmjs.com/generating-provenance-statements
> ci: add provenance to npm packages

- CHANGELOG.md
- package-lock.json
- package.json
- src/index.js
- src/plugins.js
- tests/plugins.test.js
When Prettier v3 was release the plugin `prettier-plugin-twig-melody` wasn't updated. A community fork has appeared and been published so now we can enable support for it.
Fixes #254
> Re-enable support for Twig / Melody

- CHANGELOG.md
- src/config.js
This fixes an issue where running Prettier against a Tailwind v4 project didn't load the v4 config on Windows but instead loaded the built-in v3 fallback version.
Fixes #264
> Fix detection of v4 projects on Windows

- CHANGELOG.md
- src/index.js
- src/options.js
- src/sorting.js
- tests/format.test.js
- tests/plugins.test.js
- tests/utils.js
This PR introduces two new features to the plugin: removal of duplicate class names and removal of excess / unncecessary whitespace.
This feature is *always* enabled. An example of this feature in action is shown below — notice that the extra `p-4` class is removed:
```diff
- <div className="sm:p-0 p-4 p-4" />
+ <div className="p-4 sm:p-0" />
```
This was originally implemented in #70 but reverted due to issues breaking code that relies on the presence of whitespace in a class list. This PR enables this feature by default _but allows you to disable it (via `tailwindPreserveWhitespace`)_ should you run into issues. For example, the following code will be formatted as shown below:
```diff
- <div className=" sm:p-0 \n      p-4  " />
+ <div className="p-4 sm:p-0" />
```
As mentioned above, …
> Remove duplicate classes and excess whitespace

- CHANGELOG.md
- README.md
- src/index.js
- src/options.js
- src/sorting.js
- src/types.d.ts
- src/utils.js
- tests/format.test.js
- tests/plugins.test.js
This PR does a handful of things:
For example, in the following code:
```jsx
<div className={" flex " + borderClass + " underline sm:block "} />
```
After formatting the output is
```diff
- <div className={" flex " + borderClass + " underline sm:block "} />
+ <div className={"flex" + borderClass + "underline sm:block"} />
```
However, this results in invalid class names. We'll now only remove the whitespace on one side of each of the strings (depending on if it's the start or not), so the output will be:
```diff
- <div className={" flex " + borderClass + " underline sm:block "} />
+ <div className={"flex " + borderClass + " underline sm:block"} />
```
This means you're less likely to need to add extra whitespace only strings or disable whitespace removal to ensure the output stays …
> Improve handling of whitespace and duplicate class removal

- CHANGELOG.md
- src/index.js
- src/sorting.js
- tests/format.test.js
The change improves the performance of removing duplicated classNames. In this pull request, I replace the indexOf and splice functions, which have O(n) time complexity, with two separate array filters and a Set().
* Before Change: O(n^2) due to the nested indexOf and splice operations within the filter method.
* After Change: O(n) due to the use of a Set for constant-time duplicate checks and separate filtering steps.
> Only remove duplicate Tailwind classes

- CHANGELOG.md
- build.mjs
- src/index.ts
- src/utils.ts
- tests/format.test.js
Previously we'd check to see if a string literal was immediately nested inside a concat expression, for example:
```jsx
export function Example() {
return <div className={' flex ' + ' border ' + ' sm:hidden '} />
}
```
However, this breaks down when the strings being sorted are nested inside other expressions. For example, a ternary expression:
```jsx
export function Example() {
return <div class={'flex' + (standalone ? ' border ' : 'outline) + ' sm:hidden'}></div>
}
```
The way this works is if a string is nested inside a concat expression at **any level** then we'll do our best to keep the relevant whitespace. Obviously, due to runtime evaluation, we can't guarantee that all necessary whtiespace will be preserved, or that all unnecessary whitespace will be removed, but this improves the …
> Improve detection of string concatenation

- .github/workflows/prepare-release.yml
- .github/workflows/release-insiders.yml
- .github/workflows/release.yml
What it says on the tin. Node 16 is well past its EOL.
> Use Node 22 in all CI workflows

- src/index.ts
0.6.3 removed the export for the PluginOptions type. This wasn't really intentional so we're adding it back as some projects were importing it.
**However, no project _ever_ needs to use this type directly.**
We extend the appropriate interfaces in Prettier so you only ever have to type your config file export as `import("prettier").Config` or your options object as `import("prettier").Options` if you're using the programmatic API.
Fixes #291
> Export plugin options type

- src/index.ts
- tests/format.test.js
In #286 we fixed a situation in which escapes were being stripped from strings. This is because StringLiteral nodes in an expression have both escaped and unescaped values.
However, it seems that some StringLiteral nodes do not do this even though they are otherwise identical. Any StringLiteral that is the direct value of a JSX attribute does not perform any escaping.
For example, given these two JSX nodes, you will get the following as the AST:
```jsx
// The first one
;<div class={"before:content-['\\\\2248']"} />
// The second one
;<div class="before:content-['\\\\2248']" />
```
So we have to detect whether or not escaping was applied originally before doing that ourselves.
tl;dr software is hard 😅 
Fixes #294
> Only re-apply string escaping when necessary

- package-lock.json
- package.json
`ast-types` is required (https://github.com/tailwindlabs/prettier-plugin-tailwindcss/blob/efea6f924c2e57fa8f8169231e802466bb5fe9ce/src/index.ts#L6), but isn't declared as a dependency.
When using e.g. `pnpm`, it doesn't get hoisted into `node_modules` from being `recast`'s transitive dependency:
```
$ pnpm why ast-types
Legend: production dependency, optional only, dev only
prettier-plugin-tailwindcss@0.6.5 /Users/akx/build/prettier-plugin-tailwindcss
devDependencies:
recast 0.20.5
└── ast-types 0.14.2
```
so build fails:
```
> node build.mjs --minify
✘ [ERROR] Could not resolve "ast-types"
src/index.ts:6:26:
6 │ import * as astTypes from 'ast-types'
```
The same stands for `@babel/types` with a slightly different error (since it's not esbuild but dts complaining).
With these added, …
> Declare some required dependencies

- tests/fixtures.test.js
- tests/fixtures/basic/output.html
- tests/fixtures/cjs/output.html
- tests/fixtures/custom-jsx/output.jsx
- tests/fixtures/custom-vue/output.vue
- tests/fixtures/esm-explicit/output.html
- tests/fixtures/esm/output.html
- tests/fixtures/no-prettier-config/output.html
- tests/fixtures/plugins/output.html
- tests/fixtures/ts-explicit/output.html
- tests/fixtures/ts/output.html
- tests/fixtures/v3-2/output.html
This makes them easier to diff with conventional tools, and arguably easier to maintain too.
This was extracted from another possible future body of work.
> Move fixtures' expected outputs to the fixture directories

- CHANGELOG.md
- src/config.ts
- src/plugins.ts
- src/resolve.ts
We have to call `require.resolve(…)` ~10 times per call to `parse(…)`. These calls generally take microseconds however if you call `prettier.format(…)` several thousand times the times add up. It also adds up for embedded documents which call `parse(…)` a large number of times.
This PR adds a cache for these calls because generally only a few will ever be installed and Node.js will not cache misses internally.
> Add cache for known plugins

- CHANGELOG.md
- src/config.ts
We've made the design system asynchronous and need to account for that. This change is still compatible with previous v4 alphas.
> Support Tailwind CSS `v4.0.0-alpha.19`

- CHANGELOG.md
- src/utils.bench.ts
- src/utils.test.ts
- src/utils.ts
The original implementation built strings in reverse because it was logically simpler to reason about however it resulted in a significant performance and memory usage impact on larger strings with lots of changes. This could be seen in Svelte, Liquid, and Angular.
This implementation is based on #311 (thanks @ABuffSeagull) with some additional tweaks which increase performance further. I ran some benchmarks on my M3 Max (12p / 4e) and tested strings of various sizes with a different number of changes:
- a small string: 220 bytes with 2 changes
- a medium string: 4.4KB with 5 changes
- a large string: 44KB with 50 changes
- an extra large string: 4.4MB with 500 changes
- an extra large string with a large number of changes: 4.4MB with 5,000 changes
While we're not likely to run into cases …
> Improve performance of `spliceChangesIntoString`

- CHANGELOG.md
- scripts/install-fixture-deps.js
- src/config.ts
- src/resolve.ts
- tests/fixtures.test.ts
- tests/fixtures/v4/basic/app.css
- tests/fixtures/v4/basic/index.html
- tests/fixtures/v4/basic/output.html
- tests/fixtures/v4/basic/package-lock.json
- tests/fixtures/v4/basic/package.json
- tests/fixtures/v4/configs/app.css
- tests/fixtures/v4/configs/index.html
- tests/fixtures/v4/configs/my-plugin.mjs
- tests/fixtures/v4/configs/output.html
- tests/fixtures/v4/configs/package-lock.json
- tests/fixtures/v4/configs/package.json
- tests/fixtures/v4/configs/tailwind.config.mjs
Just realized we forgot to add a `loadConfig` stub when we released `v4.0.0-alpha.21`. We also need to actually fill in the implementations of loadPlugin and loadConfig so this PR does that.
We still need to add typescript support which I think means either:
- relying on `@tailwindcss/node` in the prettier plugin; OR
- loading it if it is installed
I'm not actually sure which option we should go with so I've not added typescript support yet.
> Add support for `@plugin` and `@config` in v4

- README.md
- src/config.ts
- src/index.ts
- src/options.ts
- tests/fixtures/v4/basic/package-lock.json
- tests/fixtures/v4/basic/package.json
- tests/fixtures/v4/configs/package-lock.json
- tests/fixtures/v4/configs/package.json
We're replacing the existing `tailwindEntryPoint` option with a `tailwindStylesheet` option. The existing option is just not well named and the new one feels more correct.
Some notes:
- The existing option **still works** it's just deprecated
- We'll warn when a user is using `tailwindEntryPoint` and instruct them to use `tailwindStylesheet` instead
- You may also specify the path to a CSS file in `tailwindConfig` and it'll _just work_ in a v4 project. Note: This will also warn users to use `tailwindStylesheet` but it seems like the principle of least surprise to make it work and instruct users on how to upgrade.
Fixes #318
> Introduce `tailwindStylesheet` option to replace `tailwindEntryPoint`

- CHANGELOG.md
- package-lock.json
- package.json
- src/index.ts
- src/plugins.ts
- tests/plugins.test.ts
> Replace support for `@zackad/prettier-plugin-twig-melody` with `@zackad/prettier-plugin-twig`

- CHANGELOG.md
- src/index.ts
Properties `tailwindPreserveWhitespace` and `tailwindPreserveDuplicates` are defined in [options.ts](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/blob/64373cf9c4edb260bb482a0a55b65230df3d1e8b/src/options.ts#L36-L48) but not in `PluginOptions` type.
Although these options are configurable, they didn't appear as suggestions when editing Prettier configuration.
> Add missing properties to PluginOptions type

- CHANGELOG.md
- src/index.ts
- tests/plugins.test.ts
We've been using `prettier-plugin-tailwindcss` to great effect in various Svelte projects at work, but after updating to `v0.6.x`, we noticed that Svelte components with template string classnames using newlines starting printing with **invalid syntax**, even when no class re-ordering was necessary
```svelte
<div
class={`flex
h-7.5`}
></div>
```
```svelte
<div class={`flex h-7.5`}
></div>}></div>
```
Previously reported as #303
I dug into the code, and noticed that inside the Svelte template string formatter, there is this call:
```ts
let sorted = sortTemplateLiteral(node, {
env,
removeDuplicates: false,
collapseWhitespace: false,
})
```
From this call, and from reading some of the tests, it definitely seemed like the intent was to avoid collapsing whitespace in Svelte template literals. …
> Fix erroneous template string whitespace formatting in Svelte

- scripts/install-fixture-deps.js
This pull request includes a small change to the `scripts/install-fixture-deps.js` file. The change removes an unused import statement for `fs` from the Node.js `promises` module.
> fix: remove unused import in script

- package-lock.json
- src/config.ts
- src/internal.d.ts
- src/options.ts
- tests/fixtures.test.ts
- tests/fixtures/custom-pkg-name-v3/config.js
- tests/fixtures/custom-pkg-name-v3/index.html
- tests/fixtures/custom-pkg-name-v3/output.html
- tests/fixtures/custom-pkg-name-v3/package-lock.json
- tests/fixtures/custom-pkg-name-v3/package.json
- tests/fixtures/custom-pkg-name-v4/app.css
- tests/fixtures/custom-pkg-name-v4/index.html
- tests/fixtures/custom-pkg-name-v4/output.html
- tests/fixtures/custom-pkg-name-v4/package-lock.json
- tests/fixtures/custom-pkg-name-v4/package.json
This is an internal option for our internal use and as such isn't in the published types. It may go away at a later date.
> Allow loading Tailwind CSS with a custom npm package name

- tests/fixtures.test.ts
Added line endings normalization to fixture tests to ensure consistent comparison between expected and actual outputs across different operating systems.
Test fixtures could fail when run on different operating systems (particularly Windows vs Unix-based systems) due to inconsistent line endings (`\r\n` vs `\n`). This caused false negatives in the test suite when the only difference was the line ending style.
Added a `normalizeLineEndings` function that converts all Windows-style line endings (`\r\n`) to Unix-style (`\n`) before comparing test outputs. This ensures that:
- Tests are reliable across all operating systems
- Git's automatic line ending conversion doesn't affect test results
- We're testing the actual content formatting rather than platform-specific line endings
- Verified …
> 🛠️Normalize test line endings

- CHANGELOG.md
- package-lock.json
- package.json
- src/plugins.ts
- tests/plugins.test.ts
Hi, Tailwind Team!
Thank you for the awesome plugin!
This PR updates the load order of plugins compatible with `prettier-plugin-tailwindcss` for proper interoperability.
It also removes the obsolete comment about plugins commented out due to incompatibility with Prettier 3.0.
Certain Prettier plugins, like `prettier-plugin-multiline-arrays`, may cause conflicts or unexpected behavior when loaded in the wrong order, leading to formatting issues or plugin failures.
In my case, `prettier-plugin-jsdoc` fails to apply its formatting when used with both `prettier-plugin-multiline-arrays` and `prettier-plugin-tailwindcss`, but works correctly when `prettier-plugin-tailwindcss` is excluded and the plugin order is properly set.
The [`loadCompatiblePlugins`](https://github.com/tailwindlabs/prettier- …
> fix: enforce compatible plugins load order for proper interoperability

- package-lock.json
- package.json
- src/plugins.ts
- tests/tests.ts
Prettier v3.6 already worked. ~~except for JSDoc which is either a bug in the jsdoc plugin or a bug with Prettier itself~~ (fixed in new release).
> Test against Prettier v3.6

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/plugins.ts
- tests/plugins.test.ts
The last update was over 4 years ago and pulls in old deps. Don’t think we need to keep it around.
Closes #297
> Drop support for `prettier-plugin-import-sort`

- CHANGELOG.md
- src/index.ts
- tests/tests.ts
It’s perfect since the AST doesn’t actually have information on these (it’s just strings) but this should be good enough.
Fixes #323
> Handle quote escapes in LESS when sorting `@apply`

- CHANGELOG.md
- build.mjs
- src/config.ts
- src/versions/assets.ts
- src/versions/v4.ts
- tests/fixtures.test.ts
- tests/fixtures/no-local-version/app.css
- tests/fixtures/no-local-version/index.html
- tests/fixtures/no-local-version/output.html
- tests/fixtures/no-local-version/package-lock.json
- tests/fixtures/no-local-version/package.json
- tests/fixtures/no-stylesheet-given/index.html
- tests/fixtures/no-stylesheet-given/output.html
- tests/format.test.ts
This bundles Tailwind CSS v4, it's relevant stylesheets, and intercepts their loading so users of the CDN or Standalone CLI can properly sort these without needing a local install through NPM.
**This is a breaking change**. We will still, however, search for a `tailwind.config.js` (or similar) in this scenario and load a bundled version of v3 if we find one. Specifying a stylesheet will force the plugin to load a bundled version of v4 if no local install exists.
Fixes #364
> Add bundled v4 fallback
